### ISSUE TITLE
AWS::S3::Errors::AccessDenied

### ISSUE THREAD

**Issue by geoghegan** [krobertson/deb-s3#118]
I am having terrible trouble attempting to upload files to a brand new and empty S3 bucket. The command I'm running is:

```deb-s3 upload --bucket my-private-bucket screen.deb --access-key-id=FOO --secret-access-key=BAR+BAZ --endpoint s3-eu-west-1.amazonaws.com```

The stack trace is:
```> Retrieving existing manifests
> Examining package file screen.deb
> Uploading packages and new manifests to S3
   -- Transferring pool/s/sc/screen.deb
/usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:375:in `return_or_raise': Access Denied (AWS::S3::Errors::AccessDenied)
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:476:in `client_request'
	from (eval):3:in `put_object'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-v1-1.66.0/lib/aws/s3/s3_object.rb:1765:in `write_with_put_object'
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-v1-1.66.0/lib/aws/s3/s3_object.rb:611:in `write'
	from /usr/local/lib/ruby/gems/2.4.0/gems/deb-s3-0.8.0/lib/deb/s3/utils.rb:88:in `s3_store'
	from /usr/local/lib/ruby/gems/2.4.0/gems/deb-s3-0.8.0/lib/deb/s3/manifest.rb:97:in `block in write_to_s3'
	from /usr/local/lib/ruby/gems/2.4.0/gems/deb-s3-0.8.0/lib/deb/s3/manifest.rb:95:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/deb-s3-0.8.0/lib/deb/s3/manifest.rb:95:in `write_to_s3'
	from /usr/local/lib/ruby/gems/2.4.0/gems/deb-s3-0.8.0/lib/deb/s3/cli.rb:236:in `block in upload'
	from /usr/local/lib/ruby/gems/2.4.0/gems/deb-s3-0.8.0/lib/deb/s3/cli.rb:234:in `each_value'
	from /usr/local/lib/ruby/gems/2.4.0/gems/deb-s3-0.8.0/lib/deb/s3/cli.rb:234:in `upload'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/deb-s3-0.8.0/bin/deb-s3:8:in `<top (required)>'
	from /usr/local/bin/deb-s3:22:in `load'
	from /usr/local/bin/deb-s3:22:in `<main>'
```

My IAM policy is
```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "XXXXXXXXXX",
            "Effect": "Allow",
            "Action": [
                "s3:CreateBucket",
                "s3:DeleteObject",
                "s3:DeleteObjectVersion",
                "s3:GetAccelerateConfiguration",
                "s3:GetBucketAcl",
                "s3:GetBucketCORS",
                "s3:GetBucketLocation",
                "s3:GetBucketLogging",
                "s3:GetBucketNotification",
                "s3:GetBucketPolicy",
                "s3:GetBucketRequestPayment",
                "s3:GetBucketTagging",
                "s3:GetBucketVersioning",
                "s3:GetBucketWebsite",
                "s3:GetLifecycleConfiguration",
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:GetObjectTagging",
                "s3:GetObjectTorrent",
                "s3:GetObjectVersion",
                "s3:GetObjectVersionAcl",
                "s3:GetObjectVersionTagging",
                "s3:GetObjectVersionTorrent",
                "s3:GetReplicationConfiguration",
                "s3:ListAllMyBuckets",
                "s3:ListBucket",
                "s3:ListBucketMultipartUploads",
                "s3:ListBucketVersions",
                "s3:ListMultipartUploadParts",
                "s3:PutAccelerateConfiguration",
                "s3:PutBucketAcl",
                "s3:PutBucketCORS",
                "s3:PutBucketLogging",
                "s3:PutBucketNotification",
                "s3:PutBucketPolicy",
                "s3:PutBucketRequestPayment",
                "s3:PutBucketTagging",
                "s3:PutBucketVersioning",
                "s3:PutBucketWebsite",
                "s3:PutLifecycleConfiguration",
                "s3:PutReplicationConfiguration",
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:PutObjectTagging",
                "s3:PutObjectVersionAcl",
                "s3:PutObjectVersionTagging",
                "s3:ReplicateObject",
                "s3:RestoreObject"
            ],
            "Resource": [
                "arn:aws:s3:::my-private-bucket"
            ]
        }
    ]
}
```

I don't think it's a bucket issue, as I granted the Everyone user the ability to List, Upload / Delete, View Permissions and Edit Permissions.

My list of installed gems:
```
*** LOCAL GEMS ***

aws-sdk (1.66.0)
aws-sdk-v1 (1.66.0)
bigdecimal (default: 1.3.0)
deb-s3 (0.8.0)
did_you_mean (1.1.0)
io-console (default: 0.4.6)
json (default: 2.0.2, 1.8.6)
mini_portile2 (2.1.0)
minitest (5.10.1)
net-telnet (0.1.1)
nokogiri (1.7.0.1)
openssl (default: 2.0.2)
power_assert (0.4.1)
psych (default: 2.2.2)
rake (12.0.0)
rdoc (default: 5.0.0)
test-unit (3.2.3)
thor (0.19.4)
xmlrpc (0.2.1)
```

I've tried altering the IAM permissions, ending up with the rather generous permissions above, to no avail.

**Comment by geoghegan** [comment]
This looks to be permissions based. I used my own, Admin, IAM details and was able to upload fine - so what are the required policies needed to make this work?

**Comment by mands** [comment]
+1 - hitting the same problem with an IAM user that has the following policy and works with `aws s3` to put/sync files (using the admin user works fine)

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::xxx/*",
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::xxx/*",
            ]
        }
    ]
}
```

**Comment by mands** [comment]
Actually, following on from the previous poster, the following IAM policy worked,

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::BUCKETNAME",
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:DeleteObjectVersion",
                "s3:GetObjectAcl",
                "s3:GetObjectTagging",
                "s3:GetObjectTorrent",
                "s3:GetObjectVersion",
                "s3:GetObjectVersionAcl",
                "s3:GetObjectVersionTagging",
                "s3:GetObjectVersionTorrent",
                "s3:PutObjectAcl",
                "s3:PutObjectTagging",
                "s3:PutObjectVersionAcl",
                "s3:PutObjectVersionTagging",
                "s3:ReplicateObject",
                "s3:RestoreObject"
            ],
            "Resource": [
                "arn:aws:s3:::BUCKETNAME/*"
            ]
        }
    ]
}
```

**Comment by geoghegan** [comment]
Thanks @mands ! That policy did the trick

**Comment by rjbrown99** [comment]
Also check the date and time of your system. I was using a VM with a local date/time in the past (based on suspend/resume) and that manifest itself in a Forbidden error. ntpdate is your friend.

**Comment by gevial** [comment]
Just hit this error and spent like 2 hours to figure out what's going on. The reason was that Amazon added new security feature enabled by default:
```
Block new public ACLs and uploading public objects 
```
Disabling this made upload successful.

**Comment by viganapa** [comment]
Thanks gevial. That helped!
