### ISSUE TITLE
error in deb-s3 verify

### ISSUE THREAD

**Issue by msupinodn** [krobertson/deb-s3#150]
running deb-s3 verify on a s3 bucket yells

>> Retrieving existing manifests
>> Checking for missing packages in: stable/main amd64
Traceback (most recent call last):
	12: from /usr/local/bin/deb-s3:23:in `<main>'
	11: from /usr/local/bin/deb-s3:23:in `load'
	10: from /var/lib/gems/2.5.0/gems/deb-s3-0.10.0/bin/deb-s3:9:in `<top (required)>'
	 9: from /var/lib/gems/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	 8: from /var/lib/gems/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	 7: from /var/lib/gems/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	 6: from /var/lib/gems/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	 5: from /var/lib/gems/2.5.0/gems/deb-s3-0.10.0/lib/deb/s3/cli.rb:510:in `verify'
	 4: from /var/lib/gems/2.5.0/gems/deb-s3-0.10.0/lib/deb/s3/cli.rb:510:in `each'
	 3: from /var/lib/gems/2.5.0/gems/deb-s3-0.10.0/lib/deb/s3/cli.rb:517:in `block in verify'
	 2: from /var/lib/gems/2.5.0/gems/deb-s3-0.10.0/lib/deb/s3/cli.rb:517:in `each'
	 1: from /var/lib/gems/2.5.0/gems/deb-s3-0.10.0/lib/deb/s3/cli.rb:518:in `block (2 levels) in verify'
/var/lib/gems/2.5.0/gems/deb-s3-0.10.0/lib/deb/s3/package.rb:134:in `url_filename_encoded': wrong number of arguments (given 0, expected 1) (ArgumentError)

**Comment by Vasil-Petrov** [comment]
This bug is from Jul 23, 2018. Any plans for fixing it ?

**Comment by Kalmalyzer** [comment]
(This is fixed in PR #151)
