### ISSUE TITLE
Can't upload packages built with Ubuntu Bionic

### ISSUE THREAD

**Issue by erikhh** [krobertson/deb-s3#160]
When I try to `deb-s3 upload` a package that we built on Ubuntu Bionic deb-s3 errors like so:

```
Failed to find control data in .deb with ar, trying tar.
tar: control.tar.gz: Not found in archive
tar: Error exit delayed from previous errors.
>> Lock released.
Traceback (most recent call last):
	14: from /usr/local/bin/deb-s3:23:in `<main>'
	13: from /usr/local/bin/deb-s3:23:in `load'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/deb-s3-0.10.0/bin/deb-s3:9:in `<top (required)>'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/deb-s3-0.10.0/lib/deb/s3/cli.rb:188:in `upload'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/deb-s3-0.10.0/lib/deb/s3/cli.rb:188:in `each'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/deb-s3-0.10.0/lib/deb/s3/cli.rb:190:in `block in upload'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/deb-s3-0.10.0/lib/deb/s3/package.rb:46:in `parse_file'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/deb-s3-0.10.0/lib/deb/s3/package.rb:74:in `extract_control'
	 2: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/tmpdir.rb:89:in `mktmpdir'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/deb-s3-0.10.0/lib/deb/s3/package.rb:76:in `block in extract_control'
/usr/local/lib/ruby/gems/2.5.0/gems/deb-s3-0.10.0/lib/deb/s3/package.rb:76:in `read': No such file or directory @ rb_sysopen - /var/folders/8c/yh7rr_5s04g53m86j5b6ts3w0000gn/T/d20181017-72869-1boiz7s/control (Errno::ENOENT)
```

When I rebuilt the same package on Ubuntu Xenial it uploads fine.
On Ubuntu Bionic the dpkg-deb version is 1.19.0.5 (amd64).
On Ubuntu Xenial the dpkg-deb version is 1.18.4 (amd64).

It seems that `control.tar.gz` is called `control.tar.xz` in the newer version. The same is true for `data.tar.gz` which is now called `data.tar.xz` on Bionic.

**Comment by carlhoerberg** [comment]
Seems to be fixed in https://github.com/krobertson/deb-s3/pull/158

**Comment by kpmueller** [comment]
Ran into this issue today as well

**Comment by P05TPWND** [comment]
> Seems to be fixed in #158

> Ran into this issue today as well

I too ran into this problem today...
It seems the fix was never merged into the master branch (likely due to this no longer being maintained). That said, I went to my local installation of packages.rb (`/Library/Ruby/Gems/2.6.0/gems/deb-s3-0.10.0/lib/deb/s3/package.rb` on Mac) and copied the changes from this [commit](https://github.com/braxton9460/deb-s3/commit/877bdb13b510d0232aea1e4cad63e569ef29d0e6) which resolved the issue for me (Mac OSX 10.15.5)
