### ISSUE TITLE
i18n: package info with utf8 chars prevents upload

### ISSUE THREAD

**Issue by mcbain** [krobertson/deb-s3#34]
```
/var/lib/gems/1.9.1/gems/deb-s3-0.6.1/lib/deb/s3/package.rb:237:in `[]': invalid byte sequence in US-ASCII (ArgumentError)
```

I'm trying to upload the latest nodejs deb in my s3 repo. 
In the Maintainer field there are some utf8 chars.

Less output:

```
nodejs_0.10.28-1chl1~quantal1_i386.deb:
 new debian package, version 2.0.
 size 5619768 bytes: control archive=34984 bytes.
      25 bytes,     1 lines      conffiles            
     861 bytes,    22 lines      control              
  122444 bytes,  1283 lines      md5sums              
     282 bytes,    17 lines   *  postinst             #!/bin/sh
     240 bytes,    13 lines   *  prerm                #!/bin/sh
 Package: nodejs
 Version: 0.10.28-1chl1~quantal1
 Architecture: i386
 Maintainer: J<C3><A9>r<C3><A9>my Lal <kapouer@melix.org>
 Installed-Size: 16654
 Depends: libc6 (>= 2.15), libgcc1 (>= 1:4.1.1), libstdc++6 (>= 4.1.1), rlwrap
 Conflicts: nodejs-dev, npm
 Replaces: nodejs-dev, npm
 Provides: nodejs-dev, npm
 Section: web
 Priority: extra
 Homepage: http://nodejs.org/
```

**Comment by kedare** [comment]
Hello,

Are you sure this has been fixed ? I just had the same issue with a package I try to upload :+1: 

/var/lib/gems/2.1.0/gems/deb-s3-0.7.1/lib/deb/s3/package.rb:283:in `block (2 levels) in parse_control': invalid byte sequence in US-ASCII (ArgumentError)

There are special characters in the author's name
