### ISSUE TITLE
Upload only working in one region (us-east-1), --endpoint not working as expect

### ISSUE THREAD

**Issue by yangye1947** [krobertson/deb-s3#91]
Here is what I tried. my.oregon.bucket is hosted in Oregon. I tried the upload command with and without the endpoint "--endpoint=s3-website-us-west-2.amazonaws.com". Doesn't work for me. 
Then I setup a bucket in US standard (us-east-1) with the exactly setting as the one in Oregon except the region. It works.

Here's the error:
```
deb-s3 upload my.deb --codename=stable --component=main  --bucket=my.oregon.bucket
>> Retrieving existing manifests
/Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:375:in `return_or_raise': AWS::Errors::Base (AWS::Errors::Base)
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:476:in `client_request'
	from (eval):3:in `head_object'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.66.0/lib/aws/s3/s3_object.rb:296:in `head'
	from /Library/Ruby/Gems/2.0.0/gems/aws-sdk-v1-1.66.0/lib/aws/s3/s3_object.rb:273:in `exists?'
	from /Library/Ruby/Gems/2.0.0/gems/deb-s3-0.7.1/lib/deb/s3/utils.rb:58:in `s3_exists?'
	from /Library/Ruby/Gems/2.0.0/gems/deb-s3-0.7.1/lib/deb/s3/utils.rb:62:in `s3_read'
	from /Library/Ruby/Gems/2.0.0/gems/deb-s3-0.7.1/lib/deb/s3/release.rb:30:in `retrieve'
	from /Library/Ruby/Gems/2.0.0/gems/deb-s3-0.7.1/lib/deb/s3/cli.rb:136:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/deb-s3-0.7.1/bin/deb-s3:8:in `<top (required)>'
	from /usr/bin/deb-s3:23:in `load'
	from /usr/bin/deb-s3:23:in `<main>'
```

**Comment by JamieCressey** [comment]
Try:

`--endpoint s3-us-west-2.amazonaws.com`

No need for "website" in the URL
